// Define sample property data for the property details page
export const properties = [
  {
    id: "1",
    title: "Luxury Villa with Pool",
    address: "45 Mikocheni St, Dar es Salaam, TZ",
    price: "TZS 950,000,000",
    description:
      "Stunning villa with private pool and tropical garden in the heart of Mikocheni.",
    bedrooms: 5,
    bathrooms: 4,
    area: 3200,
    yearBuilt: 2020,
    propertyType: "Villa",
    lotSize: "0.5 acres",
    garage: "3-car attached",
    images: [
      "/images/property-1.jpg",
      "/images/property-2.jpg",
      "/images/property-3.jpg",
      "/images/property-4.jpg",
    ],
    features: [
      "Infinity Pool",
      "Smart Home System",
      "Home Theater",
      "Wine Cellar",
      "Gourmet Kitchen",
      "Outdoor Kitchen",
      "Fireplace",
      "Walk-in Closets",
      "High Ceilings",
      "Mountain Views",
    ],
    agent: {
      name: "Asha Mwinyi",
      phone: "+255 765 123 456",
      email: "asha.mwinyi@skylinerealty.co.tz",
      image: "/images/agent-jane.jpg",
    },
  },
  {
    id: "2",
    title: "Modern Apartment in Masaki",
    address: "12 Chole Rd, Masaki, Dar es Salaam, TZ",
    price: "TZS 680,000,000",
    description:
      "Spacious apartment with ocean views and modern amenities in Masaki.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    yearBuilt: 2022,
    propertyType: "Apartment",
    lotSize: "0.2 acres",
    garage: "1-car assigned",
    images: [
      "/images/property-2.jpg",
      "/images/property-3.jpg",
      "/images/property-5.jpg",
    ],
    features: [
      "Ocean Views",
      "Modern Kitchen",
      "Balcony",
      "Shared Pool",
      "Gym Access",
    ],
    agent: {
      name: "Juma Mwakalinga",
      phone: "+255 678 789 012",
      email: "juma.mwakalinga@skylinerealty.co.tz",
      image: "/images/agent-john.jpg",
    },
  },
  {
    id: "3",
    title: "Family Home in Arusha",
    address: "88 Sokoine Rd, Arusha, TZ",
    price: "TZS 350,000,000",
    description:
      "Comfortable family home with a large garden and mountain views in Arusha.",
    bedrooms: 4,
    bathrooms: 3,
    area: 2000,
    yearBuilt: 2018,
    propertyType: "House",
    lotSize: "0.7 acres",
    garage: "2-car attached",
    images: [
      "/images/property-3.jpg",
      "/images/property-6.jpg",
      "/images/property-1.jpg",
    ],
    features: [
      "Large Garden",
      "Mountain Views",
      "Fireplace",
      "Quiet Neighborhood",
    ],
    agent: {
      name: "Neema Mushi",
      phone: "+255 787 456 789",
      email: "neema.mushi@skylinerealty.co.tz",
      image: "/images/agent-maria.jpg",
    },
  },
  {
    id: "4",
    title: "Beachfront Cottage",
    address: "23 Nungwi Beach, Zanzibar, TZ",
    price: "TZS 750,000,000",
    description:
      "Charming cottage with direct beach access and stunning ocean views in Zanzibar.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    yearBuilt: 2015,
    propertyType: "Cottage",
    lotSize: "0.3 acres",
    garage: "1-car detached",
    images: [
      "/images/property-4.jpg",
      "/images/property-1.jpg",
      "/images/property-6.jpg",
    ],
    features: [
      "Beach Access",
      "Ocean Views",
      "Private Patio",
      "Tropical Garden",
    ],
    agent: {
      name: "Baraka Mtemi",
      phone: "+255 754 987 654",
      email: "baraka.mtemi@skylinerealty.co.tz",
      image: "/images/agent-robert.jpg",
    },
  },
  {
    id: "5",
    title: "Downtown Loft",
    address: "5 Samora Ave, City Centre, Dar es Salaam, TZ",
    price: "TZS 480,000,000",
    description:
      "Contemporary loft in the heart of Dar es Salaam with city views.",
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    yearBuilt: 2021,
    propertyType: "Loft",
    lotSize: "0.1 acres",
    garage: "Parking Available",
    images: [
      "/images/property-5.jpg",
      "/images/property-2.jpg",
      "/images/property-4.jpg",
    ],
    features: [
      "City Views",
      "Modern Design",
      "Close to Amenities",
      "High Ceilings",
    ],
    agent: {
      name: "Fatma Nyerere",
      phone: "+255 713 234 567",
      email: "fatma.nyerere@skylinerealty.co.tz",
      image: "/images/agent-sarah.jpg",
    },
  },
  {
    id: "6",
    title: "Lake View Bungalow",
    address: "77 Capri Point, Mwanza, TZ",
    price: "TZS 550,000,000",
    description:
      "Beautiful bungalow with panoramic views of Lake Victoria in Mwanza.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    yearBuilt: 2019,
    propertyType: "Bungalow",
    lotSize: "0.6 acres",
    garage: "2-car detached",
    images: [
      "/images/property-6.jpg",
      "/images/property-3.jpg",
      "/images/property-5.jpg",
    ],
    features: [
      "Lake Views",
      "Spacious Yard",
      "Quiet Location",
      "Modern Interior",
    ],
    agent: {
      name: "Salim Kweka",
      phone: "+255 784 567 890",
      email: "salim.kweka@skylinerealty.co.tz",
      image: "/images/agent-david.jpg",
    },
  },
];
